[project]
name = "agentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.129.0",
    "langchain-google-genai>=4.2.0",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.41.0",
]
